prSections:
    - title: Envoy Web PRs
      filters: is:open repo:appropos/envoy-web
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 100
    prsLimit: 40
    prApproveComment: Approved
    issuesLimit: 40
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings:
    prs:
      - key: i
        command: jira issue view $(echo {{.HeadRefName}} | sed -nE 's|.*(EP-[0-9]+).*|\1|p') --comments 50
repoPaths: {}
theme:
    ui:
        sectionsShowCount: true
        table:
            showSeparator: true
            compact: false
    colors:
        # text:
        #     secondary: "#ff0000"
        # background:
        #     selected: "#ff0000"
pager:
    diff: diffnav
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
